<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MapujTo | Přihlášení</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/styl.css">
</head>
<body>

<p>TEST FUNKČNOSTI</p>

</body>
<h2>Vložit nový výlet</h2>
<form method="post">
    <label for="name_trip">Název výletu:</label>
    <input type="text" name="name_trip" required><br>

    <label for="length">Délka (km):</label>
    <input type="number" step="0.1" name="length" required><br>

    <label for="time">Čas (hh:mm:ss):</label>
    <input type="time" name="time" required><br>

    <label for="creator">ID autora:</label>
    <input type="number" name="creator" required><br>

    <label for="difficulty">Obtížnost (1-5):</label>
    <input type="number" name="difficulty" min="1" max="5" required><br>

    <input type="submit" name="vloz_vylet" value="Vložit výlet">
</form>
