<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href=".\img\loga\logoMain.png">
    <title>MapujTo</title>
</head>
<body>
    <?php
        $this->kontroler->vypisPohled();
    ?>
</body>
</html>