<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MapujTo | Přihlášení</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/styl.css">
</head>
<body>
    


<div class="container py-5">
    <div class="text-center mb-5">
        <form method="post">

            <fieldset>
                <legend>Přihlášení uživatele</legend>
            
            <div>
                <label for="email">Email</label>
                <input type="email" name="email" id="email">
            </div>
            

            <div>
                <label for="heslo">Heslo</label>
                <input type="password" name="password" id="password">
            </div>

                <input type="submit" value="Přihlásit">
            </fieldset>

            
        </form>
        <p>Nemáte ještě účet? <a href="register">Zaregistrujte se!</a></p>
        <p>Dostali jste se zde omylem? Vraťte se na <a href="uvod">úvod!</a></p>

    </div>
    
</div>

</body>
</html>