<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MapujTo | Přihlášení</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/styl.css">
</head>
<body>


<?php if (isset($_SESSION["User"])) { ?>
    <div class="container py-5">
        <div class="text-center mb-5">
            <h2>Vložit nový výlet</h2>
            <form method="post">
                <label for="name_trip">Název výletu:</label>
                <input type="text" name="name_trip" required><br>

                <label for="length">Délka (km):</label>
                <input type="number" step="0.1" name="length" required><br>

                <label for="time">Čas (hh:mm:ss):</label>
                <input type="time" name="time" required><br>

                <label for="difficulty">Obtížnost:</label>
                <select name="difficulty" required>
                    <?php
                    $db = new mysqli('127.0.0.1', 'root', '', 'project_trip_app');

                    // Nastavení správného kódování připojení
                    $db->set_charset("utf8mb4");

                    $result = $db->query("SELECT ID_difficulty, Name_diff FROM difficulty");
                    while ($row = $result->fetch_assoc()) {
                        echo '<option value="' . $row['ID_difficulty'] . '">' . htmlspecialchars($row['Name_diff'], ENT_QUOTES, 'UTF-8') . '</option>';
                    }
                    $db->close();
                    ?>
                </select><br>

                <input type="submit" name="vloz_vylet" value="Vložit výlet">
            </form>
        </div>
    </div>
<?php } ?>

</body>