<h1>Registrace uživatele</h1>

<form method="post">
    <fieldset>
        <legend>Registrace uživatele</legend>

    <div>
        <label for="username">Uživatelské jméno</label>
        <input type="text" name="username" id="username">
    </div>

    <div>
        <label for="country">Země</label>
        <input type="text" name="country" id="country">
    </div>

    <div>
        <label for="birthdate">Datum narození</label>
        <input type="date" name="birthdate" id="birthdate">
    </div>

    <div>
        <label for="email">Email</label>
        <input type="email" name="email" id="email">
    </div>

    <div>
        <label for="heslo">Heslo</label>
        <input type="password" name="password" id="password">
    </div>

        <input type="submit" value="Registrovat">
    </fieldset>
</form>