<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MapujTo | Registrace</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/styl.css">
</head>
<body>
    
<div class="container py-5">
    <div class="text-center mb-5">
        <form method="post">
            <fieldset>
                <legend>Registrace uživatele</legend>

            <div>
                <label for="username">Uživatelské jméno</label>
                <input type="text" name="username" id="username">
            </div>

            <div>
                <label for="country">Země</label>
                <input type="text" name="country" id="country">
            </div>

            <div>
                <label for="City">Město</label>
                <input type="text" name="city" id="city">
            </div>

            <div>
                <label for="birthdate">Datum narození</label>
                <input type="date" name="birthdate" id="birthdate">
            </div>

            <div>
                <label for="email">Email</label>
                <input type="email" name="email" id="email">
            </div>

            <div>
                <label for="heslo">Heslo</label>
                <input type="password" name="password" id="password">
            </div>

                <input type="submit" value="Registrovat">
            </fieldset>
        </form>
        <p>Máte již účet? <a href="login" style="color: black;text-decoration: none; font-weight: bold;">Přihlaste se!</a></p>
        <p>Dostali jste se zde omylem? Vraťte se na <a href="uvod" style="color: black;text-decoration: none; font-weight: bold;">úvod!</a></p>
        
    </div>
</div>

</body>
</html>