<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MVC app I3 WEA</title>
</head>
<body>
    <header> 
        <?php if (isset($_SESSION["User"])) { ?>
            Přihlášen: <?= $_SESSION["User"]["Email"] ?>
            <a href="logout">Odhlásit se</a>
        <?php } else { ?>
            <a href="login">Přihlásit se</a>
        <?php } ?>    
    </header>
    <nav>
       <ul>
            <li><a href="uvod">Úvod</a></li>
            <li><a href="body">Body</a></li>
            <li><a href="student">Studenti</a></li>
       </ul> 
    </nav>
    <?php
        $this->kontroler->vypisPohled();
    ?>
</body>
</html>