<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MapujTo | Přihlášení</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/stylZebr.css">
</head>
<body>

<div class="container py-5">
    <h2 class="text-center mb-4">🏆 Žebříček turistů</h2>
    <div class="row justify-content-center">
        <p>STRÁNKA V PŘÍPRAVĚ</p>
    </div>
</div>

</body>