<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP OOP - Body</title>
</head>
<body>
    <h1>Body</h1>

    <h2>2D</h2>
    <p>Bod <?= $p1 ?> je vzdálen od počátku o <?= $p1->distanceOrigin() ?> jednotek.</p>
    <p>Bod <?= $p2 ?> je vzdálen od počátku o <?= $p2->distanceOrigin() ?> jednotek.</p>

    <h2>3D</h2>
    <p><?= $p3 ?>: <?= $p3->distanceOrigin() ?></p>
</body>
</html>