<h1>Přihlášení uživatele</h1>

<form method="post">
    <fieldset>
        <legend>Přihlášení uživatele</legend>
    
    <div>
        <label for="email">E-mail</label>
        <input type="email" name="email" id="email">
    </div>

    <div>
        <label for="heslo">Heslo</label>
        <input type="password" name="heslo" id="heslo">
    </div>

        <input type="submit" value="Přihlásit se">
    </fieldset>
</form>