<!DOCTYPE html>
<html lang="cz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP OOP - Banka</title>
</head>
<body>
    <h1>Banka</h1>
    <h2>Klienti</h2>
        <p>Klient <?= $klient1->getName() ?> má na svém kontě <?= $klient1->getBalance()?>  Kč.</p>
        <p>Klient <?= $klient1->getName() ?> <?=$klient1->deposit(500) ?> navýšil konto na <?= $klient1->getBalance()?>  Kč.</p>
        


</body>
</html>